# gomaker
# Makefile generated by gomaker_3ec1a9e


COMMIT=$(shell git rev-parse --verify --short HEAD)
RELEASE=${NAME}_${COMMIT}
NAME=gomaker


build:
	go build -x --ldflags "-s -X main.version=$(RELEASE) "


install:
	sudo mv ${NAME} /usr/local/bin/
